services:
  postgres:
    image: postgres:18.1
    container_name: grpc-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=grpcstore
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - grpc-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: grpc-server-compose
    networks:
      - grpc-net
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/grpcstore

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: grpc-client-compose
    networks:
      - grpc-net
    environment:
      - SERVER_ADDR=server:6767
    depends_on:
      - server
    restart: "no"

networks:
  grpc-net:
    driver: bridge

volumes:
  postgres_data:
